'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import { Button, Card, Form, Input, Modal, Select, Space, Switch, Table, Tag, Typography } from 'antd';import { message } from '@/lib/antd-message';
import {DeleteOutlined,EditOutlined,EyeOutlined,ReloadOutlined,SearchOutlined,SendOutlined} from '@ant-design/icons';
import type {TablePaginationConfig} from 'antd/es/table';
import dayjs from 'dayjs';
import api from '@/lib/axios';
import styles from './tickets.module.css';
const {Text,Title}=Typography;
type TicketMessage={id:number;message:string;type:'user'|'admin';created_at:string};
type Ticket={id:number;title:string;description?:string;type:string;order_id?:string;status:string;created_at:string;updated_at:string;messages_count?:number;user?:{id:number;username:string};messages?:TicketMessage[]};
const statusMeta:Record<string,{label:string;color:string}>={pending:{label:'Chờ xử lý',color:'warning'},processing:{label:'Đang xử lý',color:'processing'},completed:{label:'Đã hoàn thành',color:'success'},closed:{label:'Đã đóng',color:'error'},open:{label:'Mở',color:'blue'}};
const typeMeta:Record<string,{label:string;color:string}>={refill:{label:'Bảo hành',color:'warning'},cancel:{label:'Hủy đơn',color:'error'},order:{label:'Đơn hàng',color:'blue'},other:{label:'Khác',color:'cyan'},orther:{label:'Khác',color:'cyan'}};
export default function AdminTicketsPage(){
 const [editForm]=Form.useForm();const [rows,setRows]=useState<Ticket[]>([]);const [loading,setLoading]=useState(true);const [search,setSearch]=useState('');const [status,setStatus]=useState<string>();const [page,setPage]=useState({current:1,pageSize:20,total:0});const [auto,setAuto]=useState(true);const [interval,setIntervalSeconds]=useState(5);const [countdown,setCountdown]=useState(5);const [viewing,setViewing]=useState<Ticket|null>(null);const [editing,setEditing]=useState<Ticket|null>(null);const [reply,setReply]=useState('');const [sending,setSending]=useState(false);const chatRef=useRef<HTMLDivElement>(null);const pageRef=useRef(page);
 const load=useCallback(async(current=1,pageSize=20,quiet=false)=>{if(!quiet)setLoading(true);try{const r=await api.get('/admin/tickets',{params:{page:current,per_page:pageSize,search:search.trim()||undefined,status}}),d=r.data.data;setRows(d.data||[]);setPage({current:d.current_page||current,pageSize:d.per_page||pageSize,total:d.total||0})}catch{if(!quiet)message.error('Không thể tải danh sách ticket.')}finally{if(!quiet)setLoading(false)}},[search,status]);
 useEffect(()=>{void Promise.resolve().then(()=>load())},[load]);
 useEffect(()=>{pageRef.current=page},[page]);
 useEffect(()=>{if(!auto||interval===0)return;const timer=window.setInterval(()=>setCountdown(old=>{if(old<=1){const currentPage=pageRef.current;void load(currentPage.current,currentPage.pageSize,true);return interval}return old-1}),1000);return()=>window.clearInterval(timer)},[auto,interval,load]);
 const detail=async(item:Ticket)=>{try{const r=await api.get(`/admin/tickets/${item.id}`);setViewing(r.data.data);setTimeout(()=>chatRef.current?.scrollTo({top:chatRef.current.scrollHeight}),0)}catch{message.error('Không thể tải hội thoại.')}};
 const openEdit=(item:Ticket)=>{setEditing(item);editForm.setFieldsValue({title:item.title,type:item.type,order_id:item.order_id,status:item.status})};
 const save=async()=>{if(!editing)return;const values=await editForm.validateFields();await api.put(`/admin/tickets/${editing.id}`,values);message.success('Đã cập nhật ticket.');setEditing(null);await load(page.current,page.pageSize)};
 const send=async()=>{if(!viewing||!reply.trim())return;setSending(true);try{await api.post(`/admin/tickets/${viewing.id}/reply`,{message:reply.trim()});setReply('');await detail(viewing);message.success('Đã gửi phản hồi.')}finally{setSending(false)}};
 const remove=(item:Ticket)=>Modal.confirm({title:`Xóa ticket #${item.id}?`,content:'Toàn bộ hội thoại sẽ bị xóa và không thể hoàn tác.',okText:'Xóa',okButtonProps:{danger:true},cancelText:'Hủy',onOk:async()=>{await api.delete(`/admin/tickets/${item.id}`);message.success('Đã xóa ticket.');await load(page.current,page.pageSize)}});
 const columns=[{title:'ID',dataIndex:'id',width:65},{title:'Thao tác',width:135,render:(_:unknown,x:Ticket)=><Space size={4}><Button size="small" type="primary" icon={<EyeOutlined/>} onClick={()=>void detail(x)}/><Button size="small" icon={<EditOutlined/>} onClick={()=>openEdit(x)}/><Button size="small" danger type="text" icon={<DeleteOutlined/>} onClick={()=>remove(x)}/></Space>},{title:'Tiêu đề',width:300,render:(_:unknown,x:Ticket)=><button className={styles.titleLink} onClick={()=>void detail(x)}>{x.title}</button>},{title:'Người gửi',width:160,render:(_:unknown,x:Ticket)=><Tag color="blue">{x.user?.username||'Đã xóa'}</Tag>},{title:'Loại',dataIndex:'type',width:130,render:(v:string)=><Tag color={(typeMeta[v]||typeMeta.other).color}>{(typeMeta[v]||typeMeta.other).label}</Tag>},{title:'Order ID',dataIndex:'order_id',width:115,render:(v?:string)=>v||'N/A'},{title:'Trạng thái',dataIndex:'status',width:145,render:(v:string)=><Tag color={(statusMeta[v]||statusMeta.closed).color}>{(statusMeta[v]||{label:v}).label}</Tag>},{title:'Tin nhắn',dataIndex:'messages_count',width:90,align:'center' as const},{title:'Thời gian',dataIndex:'created_at',width:180,render:(v:string)=>dayjs(v).format('DD/MM/YYYY HH:mm:ss')}];
 return <main className={styles.page}><header className={styles.heading}><div><Title level={2}>Quản lý vé hỗ trợ</Title><Text type="secondary">Theo dõi và phản hồi yêu cầu hỗ trợ của thành viên</Text></div></header><Card className={styles.card} title="Danh sách ticket" extra={<div className={styles.auto}><Switch size="small" checked={auto} onChange={value=>{setAuto(value);if(value)setCountdown(interval)}}/><span>Auto Load</span><Select size="small" value={interval} onChange={v=>{setIntervalSeconds(v);setCountdown(v)}} options={[1,3,5,10,30].map(v=>({value:v,label:`${v} giây`}))}/><Tag color="blue">{auto?countdown:'--'}</Tag></div>}><div className={styles.filters}><Input value={search} allowClear prefix={<SearchOutlined/>} placeholder="Tìm tiêu đề, username, Order ID..." onChange={e=>setSearch(e.target.value)} onPressEnter={()=>void load(1,page.pageSize)}/><Select allowClear value={status} placeholder="Tất cả trạng thái" onChange={setStatus} options={Object.entries(statusMeta).map(([value,meta])=>({value,label:meta.label}))}/><Button icon={<ReloadOutlined/>} onClick={()=>void load(page.current,page.pageSize)}>Làm mới</Button></div><Table rowKey="id" columns={columns} dataSource={rows} loading={loading} scroll={{x:1320}} pagination={{...page,showSizeChanger:true,locale:{items_per_page:'/ trang'},showTotal:t=>`${t} ticket`}} onChange={(p:TablePaginationConfig)=>void load(p.current||1,p.pageSize||20)}/></Card>
 <Modal width={760} open={Boolean(viewing)} title={viewing?`Ticket #${viewing.id} — ${viewing.title}`:'Chi tiết ticket'} footer={null} onCancel={()=>setViewing(null)}><div className={styles.ticketMeta}><Tag color={(typeMeta[viewing?.type||'other']||typeMeta.other).color}>{(typeMeta[viewing?.type||'other']||typeMeta.other).label}</Tag><Tag color={(statusMeta[viewing?.status||'closed']||statusMeta.closed).color}>{(statusMeta[viewing?.status||'closed']||statusMeta.closed).label}</Tag>{viewing?.order_id&&<span>Order #{viewing.order_id}</span>}</div>{viewing?.description&&<div className={styles.description}>{viewing.description}</div>}<div ref={chatRef} className={styles.chat}>{viewing?.messages?.length?viewing.messages.map(msg=><div key={msg.id} className={`${styles.message} ${msg.type==='admin'?styles.adminMessage:styles.userMessage}`}><p>{msg.message}</p><small>{dayjs(msg.created_at).format('DD/MM HH:mm')}</small></div>):<div className={styles.emptyChat}>Chưa có tin nhắn</div>}</div><Space.Compact block><Input value={reply} placeholder="Nhập tin nhắn..." onChange={e=>setReply(e.target.value)} onPressEnter={()=>void send()}/><Button type="primary" icon={<SendOutlined/>} loading={sending} onClick={()=>void send()}>Gửi</Button></Space.Compact></Modal>
 <Modal open={Boolean(editing)} title={`Chỉnh sửa ticket #${editing?.id}`} okText="Lưu" cancelText="Đóng" onOk={()=>void save()} onCancel={()=>setEditing(null)}><Form form={editForm} layout="vertical"><Form.Item name="title" label="Tiêu đề" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="type" label="Loại hỗ trợ" rules={[{required:true}]}><Select options={[{value:'order',label:'Đơn hàng'},{value:'refill',label:'Bảo hành'},{value:'cancel',label:'Hủy đơn'},{value:'other',label:'Khác'},{value:'orther',label:'Khác (dữ liệu cũ)'}]}/></Form.Item><Form.Item name="order_id" label="Mã đơn hàng"><Input/></Form.Item><Form.Item name="status" label="Trạng thái" rules={[{required:true}]}><Select options={Object.entries(statusMeta).map(([value,meta])=>({value,label:meta.label}))}/></Form.Item></Form></Modal></main>;
}
