'use client';
import {useEffect,useState} from 'react';
import { Button, Card, Form, Modal, Select, Table, Tag, Typography, Upload } from 'antd';import { message } from '@/lib/antd-message';
import {CheckSquareOutlined,CloseSquareOutlined,CloudDownloadOutlined,HistoryOutlined,InboxOutlined,QuestionCircleOutlined,SearchOutlined} from '@ant-design/icons';
import api from '@/lib/axios';import styles from './import-services.module.css';
const {Text,Title}=Typography;const {Dragger}=Upload;
type Option={id:number;name:string};type Row={service:string;name:string;category:string;type:string;rate:number;rate_format:string;min:number;max:number};
export default function ImportServicesPage(){const [form]=Form.useForm();const [categories,setCategories]=useState<Option[]>([]),[providers,setProviders]=useState<Option[]>([]),[rows,setRows]=useState<Row[]>([]),[selected,setSelected]=useState<React.Key[]>([]),[loading,setLoading]=useState(false);
useEffect(()=>{const timer=setTimeout(()=>Promise.all([api.get('/admin/resources/categories',{params:{per_page:100}}),api.get('/admin/resources/providers',{params:{per_page:100}})]).then(([a,b])=>{setCategories(a.data.data?.data||[]);setProviders(b.data.data?.data||[])}).catch(()=>message.error('Không thể tải cấu hình import.')),0);return()=>clearTimeout(timer)},[]);
const fetchRows=async()=>{try{const v=await form.validateFields();setLoading(true);const r=await api.get('/admin/service-import/source',{params:v});setRows(Array.isArray(r.data.data)?r.data.data:[]);setSelected([])}catch(e:unknown){const text=(e as {response?:{data?:{message?:string}}})?.response?.data?.message;message.error(text||'Không thể lấy dịch vụ từ Provider.')}finally{setLoading(false)}};
const doImport=()=>{if(!selected.length)return;Modal.confirm({title:'Nhập dịch vụ đã chọn?',content:`Hệ thống sẽ nhập ${selected.length} dịch vụ vào phân loại đã chọn.`,okText:'Nhập dịch vụ',cancelText:'Huỷ',onOk:async()=>{const v=form.getFieldsValue();setLoading(true);try{const r=await api.post('/admin/service-import',{category_id:v.category_id,provider_id:v.provider_id,ids:selected});if(r.data.success===false)throw new Error(r.data.message);message.success(r.data.message||'Đã nhập dịch vụ.');setSelected([])}catch(e:unknown){message.error(e instanceof Error?e.message:'Không thể nhập dịch vụ.')}finally{setLoading(false)}}})};
const columns=[{title:'Service ID',dataIndex:'service',width:110,render:(v:string)=><b>#{v}</b>},{title:'Service Name',dataIndex:'name',render:(v:string)=><Text strong>{v}</Text>},{title:'Category',dataIndex:'category',render:(v:string)=><Tag color="blue">{v}</Tag>},{title:'Service Type',dataIndex:'type',render:(v:string)=><Tag color="cyan">{v}</Tag>},{title:'Rate per/1k',dataIndex:'rate',render:(v:number)=><Text type="success" strong>${Number(v).toLocaleString('en-US')}</Text>},{title:'Rate Format',dataIndex:'rate_format',render:(v:string)=><Tag>{v||'USD'}</Tag>},{title:'Min / Max',render:(_:unknown,x:Row)=>`${x.min.toLocaleString('vi-VN')} / ${x.max.toLocaleString('vi-VN')}`}];
return <main className={styles.page}><header className={styles.heading}><div><Title level={2}>Import Services</Title><Text type="secondary">Nhập và quản lý danh sách dịch vụ từ API Provider</Text></div><div><Button icon={<QuestionCircleOutlined/>}>Hướng dẫn import</Button><Button icon={<CloudDownloadOutlined/>}>Tải file mẫu</Button></div></header><Card className={styles.card} title="Thông tin nhập"><Form form={form} layout="vertical"><div className={styles.formGrid}><Form.Item name="category_id" label="Dịch vụ" rules={[{required:true,message:'Chọn phân loại đích.'}]}><Select showSearch optionFilterProp="label" placeholder="Chọn..." options={categories.map(x=>({value:x.id,label:x.name}))}/></Form.Item><Form.Item name="provider_id" label="Provider" rules={[{required:true,message:'Chọn Provider.'}]}><Select showSearch optionFilterProp="label" placeholder="Chọn..." options={providers.map(x=>({value:x.id,label:x.name}))}/></Form.Item></div><Dragger beforeUpload={()=>false} maxCount={1} accept=".csv,.xlsx,.xls" className={styles.upload}><p><InboxOutlined/></p><b>Kéo thả file vào đây hoặc <span>chọn file</span> để upload</b><small>Hỗ trợ định dạng: .csv, .xlsx, .xls | Dung lượng tối đa: 10MB</small></Dragger><Button block type="primary" icon={<SearchOutlined/>} loading={loading} onClick={()=>void fetchRows()}>Lấy danh sách dịch vụ để import</Button></Form></Card><Card className={styles.card} title="Thông tin dịch vụ" extra={<div><Button icon={<CheckSquareOutlined/>} disabled={!rows.length||selected.length===rows.length} onClick={()=>setSelected(rows.map(item=>item.service))}>Chọn tất cả ({rows.length})</Button><Button icon={<CloseSquareOutlined/>} disabled={!selected.length} onClick={()=>setSelected([])}>Bỏ chọn</Button><Button icon={<HistoryOutlined/>}>Import history</Button><Button type="primary" icon={<CloudDownloadOutlined/>} disabled={!selected.length} loading={loading} onClick={doImport}>Chọn dịch vụ để import ({selected.length})</Button></div>}><Table rowKey="service" loading={loading} dataSource={rows} columns={columns} rowSelection={{selectedRowKeys:selected,onChange:setSelected}} scroll={{x:1100}} pagination={{pageSize:10,showSizeChanger:true}}/></Card></main>}
