'use client';
import {useCallback,useEffect,useState} from 'react';
import { Button, Card, Form, Image, Input, InputNumber, Modal, Select, Space, Table, Tag, Typography, Upload } from 'antd';import { message } from '@/lib/antd-message';
import {DeleteOutlined,EditOutlined,FolderOutlined,PlusOutlined,ReloadOutlined,SearchOutlined,UploadOutlined} from '@ant-design/icons';
import type {TablePaginationConfig} from 'antd/es/table';import type {UploadFile} from 'antd/es/upload/interface';import dayjs from 'dayjs';import api from '@/lib/axios';import styles from './product-categories.module.css';
const {Text,Title}=Typography;const {TextArea}=Input;const asset=(path?:string|null)=>path?(/^https?:/.test(path)?path:`${(process.env.NEXT_PUBLIC_API_URL||'http://127.0.0.1:8000/api').replace(/\/api\/?$/,'')}${path.startsWith('/')?'':'/'}${path}`):'';
type Category={id:number;name:string;description?:string;image?:string;status:string;sort_order:number;products_count:number;created_at:string};type CategoryForm={name:string;description?:string;status:string;sort_order:number;image?:UploadFile[]};
export default function AdminProductCategoriesPage(){const[form]=Form.useForm<CategoryForm>();const[rows,setRows]=useState<Category[]>([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[editing,setEditing]=useState<Category|null|undefined>(undefined);const[search,setSearch]=useState('');const[status,setStatus]=useState<string>();const[selected,setSelected]=useState<React.Key[]>([]);const[page,setPage]=useState({current:1,pageSize:20,total:0});
 const load=useCallback(async(current=1,pageSize=20)=>{setLoading(true);try{const r=await api.get('/admin/product-categories',{params:{page:current,per_page:pageSize,search:search.trim()||undefined,status}}),d=r.data.data;setRows(d.data||[]);setPage({current:d.current_page||current,pageSize:d.per_page||pageSize,total:d.total||0});setSelected([])}catch{message.error('Không thể tải danh mục sản phẩm.')}finally{setLoading(false)}},[search,status]);useEffect(()=>{void Promise.resolve().then(()=>load())},[load]);
 const create=()=>{setEditing(null);form.resetFields();form.setFieldsValue({sort_order:0,status:'active',image:[]})};const edit=(x:Category)=>{setEditing(x);form.setFieldsValue({name:x.name,description:x.description,sort_order:x.sort_order,status:x.status,image:[]})};
 const save=async()=>{try{const v=await form.validateFields();setSaving(true);const b=new FormData();b.append('name',v.name);b.append('sort_order',String(v.sort_order));b.append('description',v.description||'');b.append('status',v.status);const file=v.image?.[0]?.originFileObj;if(file)b.append('image',file,file.name);const r=editing?await api.post(`/admin/product-categories/${editing.id}`,b,{headers:{'Content-Type':'multipart/form-data'}}):await api.post('/admin/product-categories',b,{headers:{'Content-Type':'multipart/form-data'}});message.success(r.data.message);setEditing(undefined);await load(page.current,page.pageSize)}catch(e:unknown){if(typeof e==='object'&&e&&'errorFields'in e)return;const d=e as{response?:{data?:{message?:string;errors?:Record<string,string[]>}}};message.error(d.response?.data?.errors?Object.values(d.response.data.errors)[0]?.[0]:d.response?.data?.message||'Không thể lưu danh mục.')}finally{setSaving(false)}};
 const removeIds=(ids:React.Key[])=>Modal.confirm({title:`Xóa ${ids.length} danh mục sản phẩm?`,content:'Các sản phẩm thuộc danh mục cũng có thể bị xóa. Thao tác này không thể hoàn tác.',okText:'Xóa',cancelText:'Hủy',okButtonProps:{danger:true},onOk:async()=>{const r=ids.length===1?await api.delete(`/admin/product-categories/${String(ids[0])}`):await api.delete('/admin/product-categories',{data:{ids}});message.success(r.data.message);await load(page.current,page.pageSize)}});
 const columns=[{title:'ID',dataIndex:'id',width:65},{title:'Thao tác',width:115,render:(_:unknown,x:Category)=><Space size={4}><Button size="small" type="primary" icon={<EditOutlined/>} onClick={()=>edit(x)}/><Button size="small" danger type="text" icon={<DeleteOutlined/>} onClick={()=>removeIds([x.id])}/></Space>},{title:'Hình ảnh',width:110,render:(_:unknown,x:Category)=>x.image?<Image className={styles.image} src={asset(x.image)} alt={x.name} width={58} height={50}/>:<div className={styles.noImage}><FolderOutlined/></div>},{title:'Tên danh mục',width:310,render:(_:unknown,x:Category)=><div className={styles.name}><button onClick={()=>edit(x)}>{x.name}</button><span>{x.description||'Không có ghi chú'}</span></div>},{title:'Sản phẩm',dataIndex:'products_count',width:110,align:'center' as const,render:(v:number)=><Tag color="blue">{v}</Tag>},{title:'Thứ tự',dataIndex:'sort_order',width:90,align:'center' as const},{title:'Trạng thái',dataIndex:'status',width:150,render:(v:string)=><Tag color={v==='active'?'success':'error'}>{v==='active'?'Hoạt động':'Ngừng hoạt động'}</Tag>},{title:'Thời gian',dataIndex:'created_at',width:180,render:(v:string)=>dayjs(v).format('DD/MM/YYYY HH:mm:ss')}];
 return <main className={styles.page}><header className={styles.heading}><div><Title level={2}>Danh mục sản phẩm</Title><Text type="secondary">Phân loại và sắp xếp sản phẩm hiển thị trên cửa hàng</Text></div></header><Card className={styles.card} title="Danh sách danh mục" extra={<Space><Button danger icon={<DeleteOutlined/>} disabled={!selected.length} onClick={()=>removeIds(selected)}>Xóa ({selected.length})</Button><Button type="primary" icon={<PlusOutlined/>} onClick={create}>Thêm mới</Button></Space>}><div className={styles.filters}><Input allowClear value={search} prefix={<SearchOutlined/>} placeholder="Tìm tên hoặc ghi chú..." onChange={e=>setSearch(e.target.value)} onPressEnter={()=>void load(1,page.pageSize)}/><Select allowClear value={status} placeholder="Tất cả trạng thái" onChange={setStatus} options={[{value:'active',label:'Hoạt động'},{value:'inactive',label:'Ngừng hoạt động'}]}/><Button icon={<ReloadOutlined/>} onClick={()=>void load(page.current,page.pageSize)}>Làm mới</Button></div><Table rowKey="id" rowSelection={{selectedRowKeys:selected,onChange:setSelected}} columns={columns} dataSource={rows} loading={loading} scroll={{x:1130}} pagination={{...page,showSizeChanger:true,locale:{items_per_page:'/ trang'},showTotal:t=>`${t} danh mục`}} onChange={(p:TablePaginationConfig)=>void load(p.current||1,p.pageSize||20)}/></Card>
 <Modal width={650} open={editing!==undefined} title={editing?'Chỉnh sửa danh mục':'Thêm danh mục sản phẩm'} okText="Lưu" cancelText="Đóng" confirmLoading={saving} onOk={()=>void save()} onCancel={()=>setEditing(undefined)}><Form form={form} layout="vertical" requiredMark={false}><Form.Item name="name" label="Tên danh mục" rules={[{required:true,message:'Nhập tên danh mục.'}]}><Input placeholder="Tên danh mục"/></Form.Item><Form.Item name="sort_order" label="Thứ tự" rules={[{required:true}]}><InputNumber className={styles.fullWidth} precision={0}/></Form.Item><Form.Item name="description" label="Ghi chú"><TextArea rows={3} placeholder="Ghi chú"/></Form.Item><Form.Item name="image" label="Hình ảnh" valuePropName="fileList" getValueFromEvent={e=>e?.fileList}><Upload beforeUpload={()=>false} maxCount={1} accept="image/jpeg,image/png,image/gif,image/webp" listType="picture"><Button icon={<UploadOutlined/>}>Chọn ảnh</Button></Upload></Form.Item>{editing?.image&&<div className={styles.current}><Text type="secondary">Ảnh hiện tại</Text><Image src={asset(editing.image)} alt={editing.name} width={100}/></div>}<Form.Item name="status" label="Trạng thái" rules={[{required:true}]}><Select options={[{value:'active',label:'Hoạt động'},{value:'inactive',label:'Ngừng hoạt động'}]}/></Form.Item></Form></Modal></main>}
