'use client';

import { useCallback, useEffect, useState } from 'react';
import { Button, Card, Form, Image, Input, InputNumber, Modal, Select, Space, Table, Tag, Typography, Upload } from 'antd';import { message } from '@/lib/antd-message';
import { DeleteOutlined, EditOutlined, InboxOutlined, PlusOutlined, ReloadOutlined, SearchOutlined, UploadOutlined } from '@ant-design/icons';
import type { TablePaginationConfig } from 'antd/es/table';
import type { UploadFile } from 'antd/es/upload/interface';
import dayjs from 'dayjs';
import api from '@/lib/axios';
import styles from './products.module.css';

const { Text, Title } = Typography; const { TextArea } = Input;
const asset = (path?: string | null) => path ? (/^https?:/.test(path) ? path : `${(process.env.NEXT_PUBLIC_API_URL || 'http://127.0.0.1:8000/api').replace(/\/api\/?$/, '')}${path.startsWith('/') ? '' : '/'}${path}`) : '';
type Category = { id: number; name: string };
type Product = { id: number; category_id: number; sort_order: number; name: string; price: string | number; price_format?: string; description?: string; short_description?: string; data_input?: string; image?: string; status: string; created_at: string; category?: Category; stocks_count: number; available_stock_count: number; sold_stock_count: number };
type ProductForm = { category_id: number; sort_order: number; name: string; price: number; description?: string; short_description?: string; data_input?: string; status: string; image?: UploadFile[] };
type Stock = { id: number; data: string; status: string; created_at: string; buyer?: { id: number; username: string } };

export default function AdminProductsPage() {
  const [form] = Form.useForm<ProductForm>(); const [stockForm] = Form.useForm<{ data: string }>();
  const [rows, setRows] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [editing, setEditing] = useState<Product | null | undefined>(undefined); const [search, setSearch] = useState('');
  const [category, setCategory] = useState<number>(); const [status, setStatus] = useState<string>();
  const [page, setPage] = useState({ current: 1, pageSize: 20, total: 0 });
  const [stockProduct, setStockProduct] = useState<Product | null>(null); const [stocks, setStocks] = useState<Stock[]>([]);
  const [stockLoading, setStockLoading] = useState(false); const [stockPage, setStockPage] = useState({ current: 1, pageSize: 20, total: 0 });
  const [stockStats, setStockStats] = useState({ available: 0, sold: 0 }); const [selectedStocks, setSelectedStocks] = useState<React.Key[]>([]); const [addingStock, setAddingStock] = useState(false);

  const loadCategories = useCallback(async () => { try { const response = await api.get('/admin/products/categories'); setCategories(response.data.data || []); } catch { message.error('Không thể tải danh mục sản phẩm.'); } }, []);
  const load = useCallback(async (current = 1, pageSize = 20) => { setLoading(true); try { const response = await api.get('/admin/products', { params: { page: current, per_page: pageSize, search: search.trim() || undefined, category_id: category, status } }); const data = response.data.data; setRows(data.data || []); setPage({ current: data.current_page || current, pageSize: data.per_page || pageSize, total: data.total || 0 }); } catch { message.error('Không thể tải danh sách sản phẩm.'); } finally { setLoading(false); } }, [category, search, status]);
  useEffect(() => { void Promise.all([load(), loadCategories()]); }, [load, loadCategories]);

  const create = () => { setEditing(null); form.resetFields(); form.setFieldsValue({ sort_order: 0, status: 'active', image: [] }); };
  const edit = (item: Product) => { setEditing(item); form.setFieldsValue({ category_id: item.category_id, sort_order: item.sort_order, name: item.name, price: Number(item.price), description: item.description, short_description: item.short_description, data_input: item.data_input, status: item.status, image: [] }); };
  const save = async () => { try { const values = await form.validateFields(); setSaving(true); const body = new FormData(); body.append('category_id', String(values.category_id)); body.append('sort_order', String(values.sort_order)); body.append('name', values.name); body.append('price', String(values.price)); body.append('status', values.status); body.append('description', values.description || ''); body.append('short_description', values.short_description || ''); body.append('data_input', values.data_input || ''); const file = values.image?.[0]?.originFileObj; if (file) body.append('image', file, file.name); const response = editing ? await api.post(`/admin/products/${editing.id}`, body, { headers: { 'Content-Type': 'multipart/form-data' } }) : await api.post('/admin/products', body, { headers: { 'Content-Type': 'multipart/form-data' } }); message.success(response.data.message || 'Đã lưu sản phẩm.'); setEditing(undefined); await load(page.current, page.pageSize); } catch (error: unknown) { if (typeof error === 'object' && error && 'errorFields' in error) return; const detail = error as { response?: { data?: { message?: string; errors?: Record<string, string[]> } } }; const first = detail.response?.data?.errors ? Object.values(detail.response.data.errors)[0]?.[0] : undefined; message.error(first || detail.response?.data?.message || 'Không thể lưu sản phẩm.'); } finally { setSaving(false); } };
  const remove = (item: Product) => Modal.confirm({ title: `Xóa sản phẩm ${item.name}?`, content: 'Kho hàng liên quan cũng sẽ bị xóa và không thể hoàn tác.', okText: 'Xóa', cancelText: 'Hủy', okButtonProps: { danger: true }, onOk: async () => { await api.delete(`/admin/products/${item.id}`); message.success('Đã xóa sản phẩm.'); await load(page.current, page.pageSize); } });

  const loadStocks = async (product: Product, current = 1, pageSize = 20) => { setStockLoading(true); try { const response = await api.get(`/admin/products/${product.id}/stocks`, { params: { page: current, per_page: pageSize } }); const data = response.data.data; setStocks(data.data || []); setStockStats(response.data.stats || {}); setStockPage({ current: data.current_page || current, pageSize: data.per_page || pageSize, total: data.total || 0 }); setSelectedStocks([]); } catch { message.error('Không thể tải kho sản phẩm.'); } finally { setStockLoading(false); } };
  const openStocks = (product: Product) => { setStockProduct(product); void loadStocks(product); };
  const addStocks = async () => { if (!stockProduct) return; const values = await stockForm.validateFields(); setAddingStock(true); try { const response = await api.post(`/admin/products/${stockProduct.id}/stocks`, values); message.success(response.data.message); stockForm.resetFields(); await loadStocks(stockProduct, 1, stockPage.pageSize); } finally { setAddingStock(false); } };
  const deleteStocks = () => { if (!stockProduct || !selectedStocks.length) return; Modal.confirm({ title: `Xóa ${selectedStocks.length} dữ liệu kho?`, okText: 'Xóa', cancelText: 'Hủy', okButtonProps: { danger: true }, onOk: async () => { const response = await api.delete(`/admin/products/${stockProduct.id}/stocks`, { data: { ids: selectedStocks } }); message.success(response.data.message); await loadStocks(stockProduct, stockPage.current, stockPage.pageSize); } }); };

  const columns = [
    { title: 'ID', dataIndex: 'id', width: 65 },
    { title: 'Thao tác', width: 155, render: (_: unknown, item: Product) => <Space size={4}><Button size="small" type="primary" icon={<EditOutlined />} onClick={() => edit(item)} /><Button size="small" className={styles.stockButton} icon={<InboxOutlined />} onClick={() => openStocks(item)} /><Button size="small" danger type="text" icon={<DeleteOutlined />} onClick={() => remove(item)} /></Space> },
    { title: 'Hình ảnh', width: 105, render: (_: unknown, item: Product) => item.image ? <Image className={styles.image} src={asset(item.image)} alt={item.name} width={62} height={50} /> : <div className={styles.noImage}><InboxOutlined /></div> },
    { title: 'Tên sản phẩm', width: 330, render: (_: unknown, item: Product) => <div className={styles.productName}><strong>{item.name}</strong><span>{item.category?.name || 'Chưa có danh mục'}</span></div> },
    { title: 'Giá', dataIndex: 'price_format', width: 145, render: (value: string, item: Product) => <Tag color="blue">{value || item.price}</Tag> },
    { title: 'Trạng thái', dataIndex: 'status', width: 145, render: (value: string) => <Tag color={value === 'active' ? 'success' : 'error'}>{value === 'active' ? 'Hoạt động' : 'Ngừng hoạt động'}</Tag> },
    { title: 'Tình trạng', width: 180, render: (_: unknown, item: Product) => item.available_stock_count > 0 ? <Space size={5}><Tag color="success">{item.available_stock_count} chưa bán</Tag>{item.sold_stock_count > 0 && <Tag>{item.sold_stock_count} đã bán</Tag>}</Space> : <Tag color="error">Hết hàng</Tag> },
    { title: 'Thứ tự', dataIndex: 'sort_order', width: 90, align: 'center' as const },
    { title: 'Thời gian', dataIndex: 'created_at', width: 180, render: (value: string) => dayjs(value).format('DD/MM/YYYY HH:mm:ss') },
  ];
  const stockColumns = [
    { title: 'ID', dataIndex: 'id', width: 70 }, { title: 'Dữ liệu', dataIndex: 'data', width: 440, render: (value: string) => <Input.TextArea className={styles.stockData} value={value} autoSize={{ minRows: 1, maxRows: 3 }} readOnly /> },
    { title: 'Trạng thái', dataIndex: 'status', width: 130, render: (value: string) => <Tag color={value === 'available' ? 'success' : 'error'}>{value === 'available' ? 'Chưa bán' : 'Đã bán'}</Tag> },
    { title: 'Người mua', width: 150, render: (_: unknown, item: Stock) => item.buyer ? <Tag color="blue">{item.buyer.username}</Tag> : 'Chưa có' },
    { title: 'Ngày tạo', dataIndex: 'created_at', width: 175, render: (value: string) => dayjs(value).format('DD/MM/YYYY HH:mm:ss') },
  ];

  return <main className={styles.page}><header className={styles.heading}><div><Title level={2}>Quản lý sản phẩm</Title><Text type="secondary">Quản lý sản phẩm số, giá bán và dữ liệu kho hàng</Text></div></header>
    <Card className={styles.card} title="Danh sách sản phẩm" extra={<Button type="primary" icon={<PlusOutlined />} onClick={create}>Thêm mới</Button>}><div className={styles.filters}><Input allowClear value={search} prefix={<SearchOutlined />} placeholder="Tìm tên hoặc mô tả sản phẩm..." onChange={event => setSearch(event.target.value)} onPressEnter={() => void load(1, page.pageSize)} /><Select allowClear value={category} placeholder="Tất cả danh mục" onChange={setCategory} options={categories.map(item => ({ value: item.id, label: item.name }))} /><Select allowClear value={status} placeholder="Tất cả trạng thái" onChange={setStatus} options={[{ value: 'active', label: 'Hoạt động' }, { value: 'inactive', label: 'Ngừng hoạt động' }]} /><Button icon={<ReloadOutlined />} onClick={() => void load(page.current, page.pageSize)}>Làm mới</Button></div><Table rowKey="id" columns={columns} dataSource={rows} loading={loading} scroll={{ x: 1390 }} pagination={{ ...page, showSizeChanger: true, locale: { items_per_page: '/ trang' }, showTotal: total => `${total} sản phẩm` }} onChange={(next: TablePaginationConfig) => void load(next.current || 1, next.pageSize || 20)} /></Card>
    <Modal width={900} open={editing !== undefined} title={editing ? 'Chỉnh sửa sản phẩm' : 'Thêm sản phẩm mới'} okText="Lưu lại" cancelText="Đóng" confirmLoading={saving} onOk={() => void save()} onCancel={() => setEditing(undefined)}><Form form={form} layout="vertical" requiredMark={false}><div className={styles.formGrid}><Form.Item name="category_id" label="Tên danh mục" rules={[{ required: true, message: 'Chọn danh mục.' }]}><Select showSearch optionFilterProp="label" placeholder="Chọn danh mục" options={categories.map(item => ({ value: item.id, label: item.name }))} /></Form.Item><Form.Item name="sort_order" label="Thứ tự" rules={[{ required: true }]}><InputNumber className={styles.fullWidth} precision={0} /></Form.Item><Form.Item className={styles.full} name="name" label="Tên sản phẩm" rules={[{ required: true, message: 'Nhập tên sản phẩm.' }]}><Input placeholder="Nhập tên sản phẩm" /></Form.Item><Form.Item name="price" label="Giá" rules={[{ required: true, message: 'Nhập giá sản phẩm.' }]}><Space.Compact block><InputNumber className={styles.priceInput} min={0} controls={false} placeholder="Nhập giá sản phẩm" /><Button disabled>₫</Button></Space.Compact></Form.Item><Form.Item name="status" label="Trạng thái" rules={[{ required: true }]}><Select options={[{ value: 'active', label: 'Hoạt động' }, { value: 'inactive', label: 'Ngừng hoạt động' }]} /></Form.Item><Form.Item className={styles.full} name="short_description" label="Chi tiết gói (Mô tả ngắn)"><TextArea rows={3} placeholder="Nhập chi tiết gói, có thể dùng HTML" /></Form.Item><Form.Item className={styles.full} name="description" label="Mô tả đầy đủ"><TextArea rows={6} placeholder="Nhập mô tả sản phẩm, có thể dùng HTML" /></Form.Item><Form.Item className={styles.full} name="data_input" label="Dữ liệu đơn hàng" extra="Ví dụ: Tên, Số điện thoại, Địa chỉ; để trống nếu không cần khách nhập."><Input placeholder="Thông tin cần người dùng cung cấp" /></Form.Item><Form.Item className={styles.full} name="image" label="Hình ảnh" valuePropName="fileList" getValueFromEvent={event => event?.fileList}><Upload beforeUpload={() => false} maxCount={1} accept="image/jpeg,image/png,image/gif,image/webp" listType="picture"><Button icon={<UploadOutlined />}>Chọn ảnh</Button></Upload></Form.Item>{editing?.image && <div className={`${styles.full} ${styles.currentImage}`}><Text type="secondary">Ảnh hiện tại</Text><Image src={asset(editing.image)} alt={editing.name} width={120} /></div>}</div></Form></Modal>
    <Modal width={1080} open={Boolean(stockProduct)} title={`Kho hàng: ${stockProduct?.name || ''}`} footer={null} onCancel={() => setStockProduct(null)}><div className={styles.stockHeader}><Space><Tag color="success">Chưa bán: {stockStats.available}</Tag><Tag color="error">Đã bán: {stockStats.sold}</Tag></Space><Space><Button danger icon={<DeleteOutlined />} disabled={!selectedStocks.length} onClick={deleteStocks}>Xóa ({selectedStocks.length})</Button></Space></div><Card size="small" className={styles.addStock} title="Thêm dữ liệu kho"><Form form={stockForm} layout="vertical"><Form.Item name="data" rules={[{ required: true, message: 'Nhập dữ liệu kho.' }]} extra="Mỗi dòng một sản phẩm; hệ thống tự động lọc dữ liệu trùng."><TextArea rows={3} placeholder="username|password|2fa... mỗi dòng một dữ liệu" /></Form.Item><Button type="primary" icon={<PlusOutlined />} loading={addingStock} onClick={() => void addStocks()}>Thêm dữ liệu</Button></Form></Card><Table rowKey="id" rowSelection={{ selectedRowKeys: selectedStocks, onChange: setSelectedStocks }} columns={stockColumns} dataSource={stocks} loading={stockLoading} scroll={{ x: 965 }} pagination={{ ...stockPage, showSizeChanger: true, locale: { items_per_page: '/ trang' } }} onChange={(next: TablePaginationConfig) => stockProduct && void loadStocks(stockProduct, next.current || 1, next.pageSize || 20)} /></Modal>
  </main>;
}
